name: "Pull Request Label Enforcer"
author: "Onemind Services LLC"
description: "Verify that the PR has at least one label"
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  github-token:
    description: "The GitHub token"
    required: true
  fail-check:
    description: "Fails the action check"
    required: false
    default: "true"
  min-labels:
    description: "Minimum number of labels needed on the PR"
    required: false
    default: "1"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.fail-check }}
    - ${{ inputs.min-labels }}
